//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PabInvestNew.CreditinfoService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XmlSchemaEnum", Namespace="http://cb4.creditinfosolutions.com/")]
    public enum XmlSchemaEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BasicBatchSchema = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullBatchSchema = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchResponseSchema = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchResponseStatusSchema = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationSchema = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MonitorSchema = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogSchema = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VersionSchema = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchPriorityClassEnum", Namespace="http://cb4.creditinfosolutions.com/")]
    public enum BatchPriorityClassEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Interactive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchProcessing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalProcessing = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cb4.creditinfosolutions.com/", ConfigurationName="CreditinfoService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/HelloWorld", ReplyAction="*")]
        PabInvestNew.CreditinfoService.HelloWorldResponse HelloWorld(PabInvestNew.CreditinfoService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.HelloWorldResponse> HelloWorldAsync(PabInvestNew.CreditinfoService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/GetLogBySeverity", ReplyAction="*")]
        PabInvestNew.CreditinfoService.GetLogBySeverityResponse GetLogBySeverity(PabInvestNew.CreditinfoService.GetLogBySeverityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/GetLogBySeverity", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetLogBySeverityResponse> GetLogBySeverityAsync(PabInvestNew.CreditinfoService.GetLogBySeverityRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUpload", ReplyAction="*")]
        PabInvestNew.CreditinfoService.BatchUploadResponse BatchUpload(PabInvestNew.CreditinfoService.BatchUploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUpload", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadResponse> BatchUploadAsync(PabInvestNew.CreditinfoService.BatchUploadRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUploadWait", ReplyAction="*")]
        PabInvestNew.CreditinfoService.BatchUploadWaitResponse BatchUploadWait(PabInvestNew.CreditinfoService.BatchUploadWaitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUploadWait", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadWaitResponse> BatchUploadWaitAsync(PabInvestNew.CreditinfoService.BatchUploadWaitRequest request);
        
        // CODEGEN: Generating message contract since element name filter from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/FilterBatchUpload", ReplyAction="*")]
        PabInvestNew.CreditinfoService.FilterBatchUploadResponse FilterBatchUpload(PabInvestNew.CreditinfoService.FilterBatchUploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/FilterBatchUpload", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.FilterBatchUploadResponse> FilterBatchUploadAsync(PabInvestNew.CreditinfoService.FilterBatchUploadRequest request);
        
        // CODEGEN: Generating message contract since element name batchId from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchResponse", ReplyAction="*")]
        PabInvestNew.CreditinfoService.BatchResponseResponse BatchResponse(PabInvestNew.CreditinfoService.BatchResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchResponse", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchResponseResponse> BatchResponseAsync(PabInvestNew.CreditinfoService.BatchResponseRequest request);
        
        // CODEGEN: Generating message contract since element name AuthorizationResult from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/Authorization", ReplyAction="*")]
        PabInvestNew.CreditinfoService.AuthorizationResponse Authorization(PabInvestNew.CreditinfoService.AuthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/Authorization", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.AuthorizationResponse> AuthorizationAsync(PabInvestNew.CreditinfoService.AuthorizationRequest request);
        
        // CODEGEN: Generating message contract since element name GetVersionResult from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/GetVersion", ReplyAction="*")]
        PabInvestNew.CreditinfoService.GetVersionResponse GetVersion(PabInvestNew.CreditinfoService.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetVersionResponse> GetVersionAsync(PabInvestNew.CreditinfoService.GetVersionRequest request);
        
        // CODEGEN: Generating message contract since element name GetXmlSchemaResult from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/GetXmlSchema", ReplyAction="*")]
        PabInvestNew.CreditinfoService.GetXmlSchemaResponse GetXmlSchema(PabInvestNew.CreditinfoService.GetXmlSchemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/GetXmlSchema", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetXmlSchemaResponse> GetXmlSchemaAsync(PabInvestNew.CreditinfoService.GetXmlSchemaRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/GetLogByGuid", ReplyAction="*")]
        PabInvestNew.CreditinfoService.GetLogByGuidResponse GetLogByGuid(PabInvestNew.CreditinfoService.GetLogByGuidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/GetLogByGuid", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetLogByGuidResponse> GetLogByGuidAsync(PabInvestNew.CreditinfoService.GetLogByGuidRequest request);
        
        // CODEGEN: Generating message contract since element name adminSubscriberUnit from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/GetMonitor", ReplyAction="*")]
        PabInvestNew.CreditinfoService.GetMonitorResponse GetMonitor(PabInvestNew.CreditinfoService.GetMonitorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/GetMonitor", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetMonitorResponse> GetMonitorAsync(PabInvestNew.CreditinfoService.GetMonitorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUploadChunkBegin", ReplyAction="*")]
        long BatchUploadChunkBegin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUploadChunkBegin", ReplyAction="*")]
        System.Threading.Tasks.Task<long> BatchUploadChunkBeginAsync();
        
        // CODEGEN: Generating message contract since element name data from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUploadChunk", ReplyAction="*")]
        PabInvestNew.CreditinfoService.BatchUploadChunkResponse BatchUploadChunk(PabInvestNew.CreditinfoService.BatchUploadChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUploadChunk", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadChunkResponse> BatchUploadChunkAsync(PabInvestNew.CreditinfoService.BatchUploadChunkRequest request);
        
        // CODEGEN: Generating message contract since element name BatchUploadChunkFinishResult from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUploadChunkFinish", ReplyAction="*")]
        PabInvestNew.CreditinfoService.BatchUploadChunkFinishResponse BatchUploadChunkFinish(PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUploadChunkFinish", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadChunkFinishResponse> BatchUploadChunkFinishAsync(PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUploadChunkWait", ReplyAction="*")]
        PabInvestNew.CreditinfoService.BatchUploadChunkWaitResponse BatchUploadChunkWait(PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchUploadChunkWait", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadChunkWaitResponse> BatchUploadChunkWaitAsync(PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequest request);
        
        // CODEGEN: Generating message contract since element name BatchResponseStatusResult from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchResponseStatus", ReplyAction="*")]
        PabInvestNew.CreditinfoService.BatchResponseStatusResponse BatchResponseStatus(PabInvestNew.CreditinfoService.BatchResponseStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchResponseStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchResponseStatusResponse> BatchResponseStatusAsync(PabInvestNew.CreditinfoService.BatchResponseStatusRequest request);
        
        // CODEGEN: Generating message contract since element name BatchResponseChunkResult from namespace http://cb4.creditinfosolutions.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchResponseChunk", ReplyAction="*")]
        PabInvestNew.CreditinfoService.BatchResponseChunkResponse BatchResponseChunk(PabInvestNew.CreditinfoService.BatchResponseChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cb4.creditinfosolutions.com/BatchResponseChunk", ReplyAction="*")]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchResponseChunkResponse> BatchResponseChunkAsync(PabInvestNew.CreditinfoService.BatchResponseChunkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(PabInvestNew.CreditinfoService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(PabInvestNew.CreditinfoService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogBySeverityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogBySeverity", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.GetLogBySeverityRequestBody Body;
        
        public GetLogBySeverityRequest() {
        }
        
        public GetLogBySeverityRequest(PabInvestNew.CreditinfoService.GetLogBySeverityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class GetLogBySeverityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement data;
        
        public GetLogBySeverityRequestBody() {
        }
        
        public GetLogBySeverityRequestBody(System.Xml.Linq.XElement data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogBySeverityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogBySeverityResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.GetLogBySeverityResponseBody Body;
        
        public GetLogBySeverityResponse() {
        }
        
        public GetLogBySeverityResponse(PabInvestNew.CreditinfoService.GetLogBySeverityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class GetLogBySeverityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetLogBySeverityResult;
        
        public GetLogBySeverityResponseBody() {
        }
        
        public GetLogBySeverityResponseBody(System.Xml.Linq.XElement GetLogBySeverityResult) {
            this.GetLogBySeverityResult = GetLogBySeverityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchUploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchUpload", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchUploadRequestBody Body;
        
        public BatchUploadRequest() {
        }
        
        public BatchUploadRequest(PabInvestNew.CreditinfoService.BatchUploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchUploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement data;
        
        public BatchUploadRequestBody() {
        }
        
        public BatchUploadRequestBody(System.Xml.Linq.XElement data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchUploadResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchUploadResponseBody Body;
        
        public BatchUploadResponse() {
        }
        
        public BatchUploadResponse(PabInvestNew.CreditinfoService.BatchUploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchUploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement BatchUploadResult;
        
        public BatchUploadResponseBody() {
        }
        
        public BatchUploadResponseBody(System.Xml.Linq.XElement BatchUploadResult) {
            this.BatchUploadResult = BatchUploadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchUploadWaitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchUploadWait", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchUploadWaitRequestBody Body;
        
        public BatchUploadWaitRequest() {
        }
        
        public BatchUploadWaitRequest(PabInvestNew.CreditinfoService.BatchUploadWaitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchUploadWaitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int miliseconds;
        
        public BatchUploadWaitRequestBody() {
        }
        
        public BatchUploadWaitRequestBody(System.Xml.Linq.XElement data, int miliseconds) {
            this.data = data;
            this.miliseconds = miliseconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchUploadWaitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchUploadWaitResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchUploadWaitResponseBody Body;
        
        public BatchUploadWaitResponse() {
        }
        
        public BatchUploadWaitResponse(PabInvestNew.CreditinfoService.BatchUploadWaitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchUploadWaitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement BatchUploadWaitResult;
        
        public BatchUploadWaitResponseBody() {
        }
        
        public BatchUploadWaitResponseBody(System.Xml.Linq.XElement BatchUploadWaitResult) {
            this.BatchUploadWaitResult = BatchUploadWaitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilterBatchUploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilterBatchUpload", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.FilterBatchUploadRequestBody Body;
        
        public FilterBatchUploadRequest() {
        }
        
        public FilterBatchUploadRequest(PabInvestNew.CreditinfoService.FilterBatchUploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class FilterBatchUploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] data;
        
        public FilterBatchUploadRequestBody() {
        }
        
        public FilterBatchUploadRequestBody(string filter, byte[] data) {
            this.filter = filter;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilterBatchUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilterBatchUploadResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.FilterBatchUploadResponseBody Body;
        
        public FilterBatchUploadResponse() {
        }
        
        public FilterBatchUploadResponse(PabInvestNew.CreditinfoService.FilterBatchUploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class FilterBatchUploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement FilterBatchUploadResult;
        
        public FilterBatchUploadResponseBody() {
        }
        
        public FilterBatchUploadResponseBody(System.Xml.Linq.XElement FilterBatchUploadResult) {
            this.FilterBatchUploadResult = FilterBatchUploadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchResponseRequestBody Body;
        
        public BatchResponseRequest() {
        }
        
        public BatchResponseRequest(PabInvestNew.CreditinfoService.BatchResponseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchResponseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string batchId;
        
        public BatchResponseRequestBody() {
        }
        
        public BatchResponseRequestBody(string batchId) {
            this.batchId = batchId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResponseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchResponseResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchResponseResponseBody Body;
        
        public BatchResponseResponse() {
        }
        
        public BatchResponseResponse(PabInvestNew.CreditinfoService.BatchResponseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchResponseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement BatchResponseResult;
        
        public BatchResponseResponseBody() {
        }
        
        public BatchResponseResponseBody(System.Xml.Linq.XElement BatchResponseResult) {
            this.BatchResponseResult = BatchResponseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authorization", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.AuthorizationRequestBody Body;
        
        public AuthorizationRequest() {
        }
        
        public AuthorizationRequest(PabInvestNew.CreditinfoService.AuthorizationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AuthorizationRequestBody {
        
        public AuthorizationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizationResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.AuthorizationResponseBody Body;
        
        public AuthorizationResponse() {
        }
        
        public AuthorizationResponse(PabInvestNew.CreditinfoService.AuthorizationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class AuthorizationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement AuthorizationResult;
        
        public AuthorizationResponseBody() {
        }
        
        public AuthorizationResponseBody(System.Xml.Linq.XElement AuthorizationResult) {
            this.AuthorizationResult = AuthorizationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.GetVersionRequestBody Body;
        
        public GetVersionRequest() {
        }
        
        public GetVersionRequest(PabInvestNew.CreditinfoService.GetVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVersionRequestBody {
        
        public GetVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.GetVersionResponseBody Body;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(PabInvestNew.CreditinfoService.GetVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class GetVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetVersionResult;
        
        public GetVersionResponseBody() {
        }
        
        public GetVersionResponseBody(System.Xml.Linq.XElement GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlSchemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlSchema", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.GetXmlSchemaRequestBody Body;
        
        public GetXmlSchemaRequest() {
        }
        
        public GetXmlSchemaRequest(PabInvestNew.CreditinfoService.GetXmlSchemaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class GetXmlSchemaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public PabInvestNew.CreditinfoService.XmlSchemaEnum schema;
        
        public GetXmlSchemaRequestBody() {
        }
        
        public GetXmlSchemaRequestBody(PabInvestNew.CreditinfoService.XmlSchemaEnum schema) {
            this.schema = schema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlSchemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlSchemaResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.GetXmlSchemaResponseBody Body;
        
        public GetXmlSchemaResponse() {
        }
        
        public GetXmlSchemaResponse(PabInvestNew.CreditinfoService.GetXmlSchemaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class GetXmlSchemaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetXmlSchemaResult;
        
        public GetXmlSchemaResponseBody() {
        }
        
        public GetXmlSchemaResponseBody(System.Xml.Linq.XElement GetXmlSchemaResult) {
            this.GetXmlSchemaResult = GetXmlSchemaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogByGuidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogByGuid", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.GetLogByGuidRequestBody Body;
        
        public GetLogByGuidRequest() {
        }
        
        public GetLogByGuidRequest(PabInvestNew.CreditinfoService.GetLogByGuidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class GetLogByGuidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement data;
        
        public GetLogByGuidRequestBody() {
        }
        
        public GetLogByGuidRequestBody(System.Xml.Linq.XElement data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogByGuidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogByGuidResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.GetLogByGuidResponseBody Body;
        
        public GetLogByGuidResponse() {
        }
        
        public GetLogByGuidResponse(PabInvestNew.CreditinfoService.GetLogByGuidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class GetLogByGuidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetLogByGuidResult;
        
        public GetLogByGuidResponseBody() {
        }
        
        public GetLogByGuidResponseBody(System.Xml.Linq.XElement GetLogByGuidResult) {
            this.GetLogByGuidResult = GetLogByGuidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonitorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMonitor", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.GetMonitorRequestBody Body;
        
        public GetMonitorRequest() {
        }
        
        public GetMonitorRequest(PabInvestNew.CreditinfoService.GetMonitorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class GetMonitorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string adminSubscriberUnit;
        
        public GetMonitorRequestBody() {
        }
        
        public GetMonitorRequestBody(string adminSubscriberUnit) {
            this.adminSubscriberUnit = adminSubscriberUnit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonitorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMonitorResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.GetMonitorResponseBody Body;
        
        public GetMonitorResponse() {
        }
        
        public GetMonitorResponse(PabInvestNew.CreditinfoService.GetMonitorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class GetMonitorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetMonitorResult;
        
        public GetMonitorResponseBody() {
        }
        
        public GetMonitorResponseBody(System.Xml.Linq.XElement GetMonitorResult) {
            this.GetMonitorResult = GetMonitorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchUploadChunkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchUploadChunk", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchUploadChunkRequestBody Body;
        
        public BatchUploadChunkRequest() {
        }
        
        public BatchUploadChunkRequest(PabInvestNew.CreditinfoService.BatchUploadChunkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchUploadChunkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int partNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] data;
        
        public BatchUploadChunkRequestBody() {
        }
        
        public BatchUploadChunkRequestBody(long id, int partNumber, byte[] data) {
            this.id = id;
            this.partNumber = partNumber;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchUploadChunkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchUploadChunkResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchUploadChunkResponseBody Body;
        
        public BatchUploadChunkResponse() {
        }
        
        public BatchUploadChunkResponse(PabInvestNew.CreditinfoService.BatchUploadChunkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BatchUploadChunkResponseBody {
        
        public BatchUploadChunkResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchUploadChunkFinishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchUploadChunkFinish", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequestBody Body;
        
        public BatchUploadChunkFinishRequest() {
        }
        
        public BatchUploadChunkFinishRequest(PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchUploadChunkFinishRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public PabInvestNew.CreditinfoService.BatchPriorityClassEnum priority;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long id;
        
        public BatchUploadChunkFinishRequestBody() {
        }
        
        public BatchUploadChunkFinishRequestBody(PabInvestNew.CreditinfoService.BatchPriorityClassEnum priority, long id) {
            this.priority = priority;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchUploadChunkFinishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchUploadChunkFinishResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchUploadChunkFinishResponseBody Body;
        
        public BatchUploadChunkFinishResponse() {
        }
        
        public BatchUploadChunkFinishResponse(PabInvestNew.CreditinfoService.BatchUploadChunkFinishResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchUploadChunkFinishResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement BatchUploadChunkFinishResult;
        
        public BatchUploadChunkFinishResponseBody() {
        }
        
        public BatchUploadChunkFinishResponseBody(System.Xml.Linq.XElement BatchUploadChunkFinishResult) {
            this.BatchUploadChunkFinishResult = BatchUploadChunkFinishResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchUploadChunkWaitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchUploadChunkWait", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequestBody Body;
        
        public BatchUploadChunkWaitRequest() {
        }
        
        public BatchUploadChunkWaitRequest(PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchUploadChunkWaitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public PabInvestNew.CreditinfoService.BatchPriorityClassEnum priority;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int miliseconds;
        
        public BatchUploadChunkWaitRequestBody() {
        }
        
        public BatchUploadChunkWaitRequestBody(PabInvestNew.CreditinfoService.BatchPriorityClassEnum priority, byte[] data, int miliseconds) {
            this.priority = priority;
            this.data = data;
            this.miliseconds = miliseconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchUploadChunkWaitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchUploadChunkWaitResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchUploadChunkWaitResponseBody Body;
        
        public BatchUploadChunkWaitResponse() {
        }
        
        public BatchUploadChunkWaitResponse(PabInvestNew.CreditinfoService.BatchUploadChunkWaitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchUploadChunkWaitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] BatchUploadChunkWaitResult;
        
        public BatchUploadChunkWaitResponseBody() {
        }
        
        public BatchUploadChunkWaitResponseBody(byte[] BatchUploadChunkWaitResult) {
            this.BatchUploadChunkWaitResult = BatchUploadChunkWaitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResponseStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchResponseStatus", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchResponseStatusRequestBody Body;
        
        public BatchResponseStatusRequest() {
        }
        
        public BatchResponseStatusRequest(PabInvestNew.CreditinfoService.BatchResponseStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchResponseStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public BatchResponseStatusRequestBody() {
        }
        
        public BatchResponseStatusRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResponseStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchResponseStatusResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchResponseStatusResponseBody Body;
        
        public BatchResponseStatusResponse() {
        }
        
        public BatchResponseStatusResponse(PabInvestNew.CreditinfoService.BatchResponseStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchResponseStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement BatchResponseStatusResult;
        
        public BatchResponseStatusResponseBody() {
        }
        
        public BatchResponseStatusResponseBody(System.Xml.Linq.XElement BatchResponseStatusResult) {
            this.BatchResponseStatusResult = BatchResponseStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResponseChunkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchResponseChunk", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchResponseChunkRequestBody Body;
        
        public BatchResponseChunkRequest() {
        }
        
        public BatchResponseChunkRequest(PabInvestNew.CreditinfoService.BatchResponseChunkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchResponseChunkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int partNumber;
        
        public BatchResponseChunkRequestBody() {
        }
        
        public BatchResponseChunkRequestBody(long id, int partNumber) {
            this.id = id;
            this.partNumber = partNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResponseChunkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchResponseChunkResponse", Namespace="http://cb4.creditinfosolutions.com/", Order=0)]
        public PabInvestNew.CreditinfoService.BatchResponseChunkResponseBody Body;
        
        public BatchResponseChunkResponse() {
        }
        
        public BatchResponseChunkResponse(PabInvestNew.CreditinfoService.BatchResponseChunkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cb4.creditinfosolutions.com/")]
    public partial class BatchResponseChunkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] BatchResponseChunkResult;
        
        public BatchResponseChunkResponseBody() {
        }
        
        public BatchResponseChunkResponseBody(byte[] BatchResponseChunkResult) {
            this.BatchResponseChunkResult = BatchResponseChunkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : PabInvestNew.CreditinfoService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<PabInvestNew.CreditinfoService.ServiceSoap>, PabInvestNew.CreditinfoService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.HelloWorldResponse PabInvestNew.CreditinfoService.ServiceSoap.HelloWorld(PabInvestNew.CreditinfoService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            PabInvestNew.CreditinfoService.HelloWorldRequest inValue = new PabInvestNew.CreditinfoService.HelloWorldRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.HelloWorldRequestBody();
            PabInvestNew.CreditinfoService.HelloWorldResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.HelloWorldResponse> PabInvestNew.CreditinfoService.ServiceSoap.HelloWorldAsync(PabInvestNew.CreditinfoService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.HelloWorldResponse> HelloWorldAsync() {
            PabInvestNew.CreditinfoService.HelloWorldRequest inValue = new PabInvestNew.CreditinfoService.HelloWorldRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.HelloWorldRequestBody();
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.GetLogBySeverityResponse PabInvestNew.CreditinfoService.ServiceSoap.GetLogBySeverity(PabInvestNew.CreditinfoService.GetLogBySeverityRequest request) {
            return base.Channel.GetLogBySeverity(request);
        }
        
        public System.Xml.Linq.XElement GetLogBySeverity(System.Xml.Linq.XElement data) {
            PabInvestNew.CreditinfoService.GetLogBySeverityRequest inValue = new PabInvestNew.CreditinfoService.GetLogBySeverityRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.GetLogBySeverityRequestBody();
            inValue.Body.data = data;
            PabInvestNew.CreditinfoService.GetLogBySeverityResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).GetLogBySeverity(inValue);
            return retVal.Body.GetLogBySeverityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetLogBySeverityResponse> PabInvestNew.CreditinfoService.ServiceSoap.GetLogBySeverityAsync(PabInvestNew.CreditinfoService.GetLogBySeverityRequest request) {
            return base.Channel.GetLogBySeverityAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetLogBySeverityResponse> GetLogBySeverityAsync(System.Xml.Linq.XElement data) {
            PabInvestNew.CreditinfoService.GetLogBySeverityRequest inValue = new PabInvestNew.CreditinfoService.GetLogBySeverityRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.GetLogBySeverityRequestBody();
            inValue.Body.data = data;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).GetLogBySeverityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.BatchUploadResponse PabInvestNew.CreditinfoService.ServiceSoap.BatchUpload(PabInvestNew.CreditinfoService.BatchUploadRequest request) {
            return base.Channel.BatchUpload(request);
        }
        
        public System.Xml.Linq.XElement BatchUpload(System.Xml.Linq.XElement data) {
            PabInvestNew.CreditinfoService.BatchUploadRequest inValue = new PabInvestNew.CreditinfoService.BatchUploadRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchUploadRequestBody();
            inValue.Body.data = data;
            PabInvestNew.CreditinfoService.BatchUploadResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchUpload(inValue);
            return retVal.Body.BatchUploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadResponse> PabInvestNew.CreditinfoService.ServiceSoap.BatchUploadAsync(PabInvestNew.CreditinfoService.BatchUploadRequest request) {
            return base.Channel.BatchUploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadResponse> BatchUploadAsync(System.Xml.Linq.XElement data) {
            PabInvestNew.CreditinfoService.BatchUploadRequest inValue = new PabInvestNew.CreditinfoService.BatchUploadRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchUploadRequestBody();
            inValue.Body.data = data;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchUploadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.BatchUploadWaitResponse PabInvestNew.CreditinfoService.ServiceSoap.BatchUploadWait(PabInvestNew.CreditinfoService.BatchUploadWaitRequest request) {
            return base.Channel.BatchUploadWait(request);
        }
        
        public System.Xml.Linq.XElement BatchUploadWait(System.Xml.Linq.XElement data, int miliseconds) {
            PabInvestNew.CreditinfoService.BatchUploadWaitRequest inValue = new PabInvestNew.CreditinfoService.BatchUploadWaitRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchUploadWaitRequestBody();
            inValue.Body.data = data;
            inValue.Body.miliseconds = miliseconds;
            PabInvestNew.CreditinfoService.BatchUploadWaitResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchUploadWait(inValue);
            return retVal.Body.BatchUploadWaitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadWaitResponse> PabInvestNew.CreditinfoService.ServiceSoap.BatchUploadWaitAsync(PabInvestNew.CreditinfoService.BatchUploadWaitRequest request) {
            return base.Channel.BatchUploadWaitAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadWaitResponse> BatchUploadWaitAsync(System.Xml.Linq.XElement data, int miliseconds) {
            PabInvestNew.CreditinfoService.BatchUploadWaitRequest inValue = new PabInvestNew.CreditinfoService.BatchUploadWaitRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchUploadWaitRequestBody();
            inValue.Body.data = data;
            inValue.Body.miliseconds = miliseconds;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchUploadWaitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.FilterBatchUploadResponse PabInvestNew.CreditinfoService.ServiceSoap.FilterBatchUpload(PabInvestNew.CreditinfoService.FilterBatchUploadRequest request) {
            return base.Channel.FilterBatchUpload(request);
        }
        
        public System.Xml.Linq.XElement FilterBatchUpload(string filter, byte[] data) {
            PabInvestNew.CreditinfoService.FilterBatchUploadRequest inValue = new PabInvestNew.CreditinfoService.FilterBatchUploadRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.FilterBatchUploadRequestBody();
            inValue.Body.filter = filter;
            inValue.Body.data = data;
            PabInvestNew.CreditinfoService.FilterBatchUploadResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).FilterBatchUpload(inValue);
            return retVal.Body.FilterBatchUploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.FilterBatchUploadResponse> PabInvestNew.CreditinfoService.ServiceSoap.FilterBatchUploadAsync(PabInvestNew.CreditinfoService.FilterBatchUploadRequest request) {
            return base.Channel.FilterBatchUploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.FilterBatchUploadResponse> FilterBatchUploadAsync(string filter, byte[] data) {
            PabInvestNew.CreditinfoService.FilterBatchUploadRequest inValue = new PabInvestNew.CreditinfoService.FilterBatchUploadRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.FilterBatchUploadRequestBody();
            inValue.Body.filter = filter;
            inValue.Body.data = data;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).FilterBatchUploadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.BatchResponseResponse PabInvestNew.CreditinfoService.ServiceSoap.BatchResponse(PabInvestNew.CreditinfoService.BatchResponseRequest request) {
            return base.Channel.BatchResponse(request);
        }
        
        public System.Xml.Linq.XElement BatchResponse(string batchId) {
            PabInvestNew.CreditinfoService.BatchResponseRequest inValue = new PabInvestNew.CreditinfoService.BatchResponseRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchResponseRequestBody();
            inValue.Body.batchId = batchId;
            PabInvestNew.CreditinfoService.BatchResponseResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchResponse(inValue);
            return retVal.Body.BatchResponseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchResponseResponse> PabInvestNew.CreditinfoService.ServiceSoap.BatchResponseAsync(PabInvestNew.CreditinfoService.BatchResponseRequest request) {
            return base.Channel.BatchResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchResponseResponse> BatchResponseAsync(string batchId) {
            PabInvestNew.CreditinfoService.BatchResponseRequest inValue = new PabInvestNew.CreditinfoService.BatchResponseRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchResponseRequestBody();
            inValue.Body.batchId = batchId;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchResponseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.AuthorizationResponse PabInvestNew.CreditinfoService.ServiceSoap.Authorization(PabInvestNew.CreditinfoService.AuthorizationRequest request) {
            return base.Channel.Authorization(request);
        }
        
        public System.Xml.Linq.XElement Authorization() {
            PabInvestNew.CreditinfoService.AuthorizationRequest inValue = new PabInvestNew.CreditinfoService.AuthorizationRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.AuthorizationRequestBody();
            PabInvestNew.CreditinfoService.AuthorizationResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).Authorization(inValue);
            return retVal.Body.AuthorizationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.AuthorizationResponse> PabInvestNew.CreditinfoService.ServiceSoap.AuthorizationAsync(PabInvestNew.CreditinfoService.AuthorizationRequest request) {
            return base.Channel.AuthorizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.AuthorizationResponse> AuthorizationAsync() {
            PabInvestNew.CreditinfoService.AuthorizationRequest inValue = new PabInvestNew.CreditinfoService.AuthorizationRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.AuthorizationRequestBody();
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).AuthorizationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.GetVersionResponse PabInvestNew.CreditinfoService.ServiceSoap.GetVersion(PabInvestNew.CreditinfoService.GetVersionRequest request) {
            return base.Channel.GetVersion(request);
        }
        
        public System.Xml.Linq.XElement GetVersion() {
            PabInvestNew.CreditinfoService.GetVersionRequest inValue = new PabInvestNew.CreditinfoService.GetVersionRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.GetVersionRequestBody();
            PabInvestNew.CreditinfoService.GetVersionResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).GetVersion(inValue);
            return retVal.Body.GetVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetVersionResponse> PabInvestNew.CreditinfoService.ServiceSoap.GetVersionAsync(PabInvestNew.CreditinfoService.GetVersionRequest request) {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetVersionResponse> GetVersionAsync() {
            PabInvestNew.CreditinfoService.GetVersionRequest inValue = new PabInvestNew.CreditinfoService.GetVersionRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.GetVersionRequestBody();
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).GetVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.GetXmlSchemaResponse PabInvestNew.CreditinfoService.ServiceSoap.GetXmlSchema(PabInvestNew.CreditinfoService.GetXmlSchemaRequest request) {
            return base.Channel.GetXmlSchema(request);
        }
        
        public System.Xml.Linq.XElement GetXmlSchema(PabInvestNew.CreditinfoService.XmlSchemaEnum schema) {
            PabInvestNew.CreditinfoService.GetXmlSchemaRequest inValue = new PabInvestNew.CreditinfoService.GetXmlSchemaRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.GetXmlSchemaRequestBody();
            inValue.Body.schema = schema;
            PabInvestNew.CreditinfoService.GetXmlSchemaResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).GetXmlSchema(inValue);
            return retVal.Body.GetXmlSchemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetXmlSchemaResponse> PabInvestNew.CreditinfoService.ServiceSoap.GetXmlSchemaAsync(PabInvestNew.CreditinfoService.GetXmlSchemaRequest request) {
            return base.Channel.GetXmlSchemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetXmlSchemaResponse> GetXmlSchemaAsync(PabInvestNew.CreditinfoService.XmlSchemaEnum schema) {
            PabInvestNew.CreditinfoService.GetXmlSchemaRequest inValue = new PabInvestNew.CreditinfoService.GetXmlSchemaRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.GetXmlSchemaRequestBody();
            inValue.Body.schema = schema;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).GetXmlSchemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.GetLogByGuidResponse PabInvestNew.CreditinfoService.ServiceSoap.GetLogByGuid(PabInvestNew.CreditinfoService.GetLogByGuidRequest request) {
            return base.Channel.GetLogByGuid(request);
        }
        
        public System.Xml.Linq.XElement GetLogByGuid(System.Xml.Linq.XElement data) {
            PabInvestNew.CreditinfoService.GetLogByGuidRequest inValue = new PabInvestNew.CreditinfoService.GetLogByGuidRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.GetLogByGuidRequestBody();
            inValue.Body.data = data;
            PabInvestNew.CreditinfoService.GetLogByGuidResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).GetLogByGuid(inValue);
            return retVal.Body.GetLogByGuidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetLogByGuidResponse> PabInvestNew.CreditinfoService.ServiceSoap.GetLogByGuidAsync(PabInvestNew.CreditinfoService.GetLogByGuidRequest request) {
            return base.Channel.GetLogByGuidAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetLogByGuidResponse> GetLogByGuidAsync(System.Xml.Linq.XElement data) {
            PabInvestNew.CreditinfoService.GetLogByGuidRequest inValue = new PabInvestNew.CreditinfoService.GetLogByGuidRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.GetLogByGuidRequestBody();
            inValue.Body.data = data;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).GetLogByGuidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.GetMonitorResponse PabInvestNew.CreditinfoService.ServiceSoap.GetMonitor(PabInvestNew.CreditinfoService.GetMonitorRequest request) {
            return base.Channel.GetMonitor(request);
        }
        
        public System.Xml.Linq.XElement GetMonitor(string adminSubscriberUnit) {
            PabInvestNew.CreditinfoService.GetMonitorRequest inValue = new PabInvestNew.CreditinfoService.GetMonitorRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.GetMonitorRequestBody();
            inValue.Body.adminSubscriberUnit = adminSubscriberUnit;
            PabInvestNew.CreditinfoService.GetMonitorResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).GetMonitor(inValue);
            return retVal.Body.GetMonitorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetMonitorResponse> PabInvestNew.CreditinfoService.ServiceSoap.GetMonitorAsync(PabInvestNew.CreditinfoService.GetMonitorRequest request) {
            return base.Channel.GetMonitorAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.GetMonitorResponse> GetMonitorAsync(string adminSubscriberUnit) {
            PabInvestNew.CreditinfoService.GetMonitorRequest inValue = new PabInvestNew.CreditinfoService.GetMonitorRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.GetMonitorRequestBody();
            inValue.Body.adminSubscriberUnit = adminSubscriberUnit;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).GetMonitorAsync(inValue);
        }
        
        public long BatchUploadChunkBegin() {
            return base.Channel.BatchUploadChunkBegin();
        }
        
        public System.Threading.Tasks.Task<long> BatchUploadChunkBeginAsync() {
            return base.Channel.BatchUploadChunkBeginAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.BatchUploadChunkResponse PabInvestNew.CreditinfoService.ServiceSoap.BatchUploadChunk(PabInvestNew.CreditinfoService.BatchUploadChunkRequest request) {
            return base.Channel.BatchUploadChunk(request);
        }
        
        public void BatchUploadChunk(long id, int partNumber, byte[] data) {
            PabInvestNew.CreditinfoService.BatchUploadChunkRequest inValue = new PabInvestNew.CreditinfoService.BatchUploadChunkRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchUploadChunkRequestBody();
            inValue.Body.id = id;
            inValue.Body.partNumber = partNumber;
            inValue.Body.data = data;
            PabInvestNew.CreditinfoService.BatchUploadChunkResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchUploadChunk(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadChunkResponse> PabInvestNew.CreditinfoService.ServiceSoap.BatchUploadChunkAsync(PabInvestNew.CreditinfoService.BatchUploadChunkRequest request) {
            return base.Channel.BatchUploadChunkAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadChunkResponse> BatchUploadChunkAsync(long id, int partNumber, byte[] data) {
            PabInvestNew.CreditinfoService.BatchUploadChunkRequest inValue = new PabInvestNew.CreditinfoService.BatchUploadChunkRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchUploadChunkRequestBody();
            inValue.Body.id = id;
            inValue.Body.partNumber = partNumber;
            inValue.Body.data = data;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchUploadChunkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.BatchUploadChunkFinishResponse PabInvestNew.CreditinfoService.ServiceSoap.BatchUploadChunkFinish(PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequest request) {
            return base.Channel.BatchUploadChunkFinish(request);
        }
        
        public System.Xml.Linq.XElement BatchUploadChunkFinish(PabInvestNew.CreditinfoService.BatchPriorityClassEnum priority, long id) {
            PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequest inValue = new PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequestBody();
            inValue.Body.priority = priority;
            inValue.Body.id = id;
            PabInvestNew.CreditinfoService.BatchUploadChunkFinishResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchUploadChunkFinish(inValue);
            return retVal.Body.BatchUploadChunkFinishResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadChunkFinishResponse> PabInvestNew.CreditinfoService.ServiceSoap.BatchUploadChunkFinishAsync(PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequest request) {
            return base.Channel.BatchUploadChunkFinishAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadChunkFinishResponse> BatchUploadChunkFinishAsync(PabInvestNew.CreditinfoService.BatchPriorityClassEnum priority, long id) {
            PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequest inValue = new PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchUploadChunkFinishRequestBody();
            inValue.Body.priority = priority;
            inValue.Body.id = id;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchUploadChunkFinishAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.BatchUploadChunkWaitResponse PabInvestNew.CreditinfoService.ServiceSoap.BatchUploadChunkWait(PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequest request) {
            return base.Channel.BatchUploadChunkWait(request);
        }
        
        public byte[] BatchUploadChunkWait(PabInvestNew.CreditinfoService.BatchPriorityClassEnum priority, byte[] data, int miliseconds) {
            PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequest inValue = new PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequestBody();
            inValue.Body.priority = priority;
            inValue.Body.data = data;
            inValue.Body.miliseconds = miliseconds;
            PabInvestNew.CreditinfoService.BatchUploadChunkWaitResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchUploadChunkWait(inValue);
            return retVal.Body.BatchUploadChunkWaitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadChunkWaitResponse> PabInvestNew.CreditinfoService.ServiceSoap.BatchUploadChunkWaitAsync(PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequest request) {
            return base.Channel.BatchUploadChunkWaitAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchUploadChunkWaitResponse> BatchUploadChunkWaitAsync(PabInvestNew.CreditinfoService.BatchPriorityClassEnum priority, byte[] data, int miliseconds) {
            PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequest inValue = new PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchUploadChunkWaitRequestBody();
            inValue.Body.priority = priority;
            inValue.Body.data = data;
            inValue.Body.miliseconds = miliseconds;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchUploadChunkWaitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.BatchResponseStatusResponse PabInvestNew.CreditinfoService.ServiceSoap.BatchResponseStatus(PabInvestNew.CreditinfoService.BatchResponseStatusRequest request) {
            return base.Channel.BatchResponseStatus(request);
        }
        
        public System.Xml.Linq.XElement BatchResponseStatus(long id) {
            PabInvestNew.CreditinfoService.BatchResponseStatusRequest inValue = new PabInvestNew.CreditinfoService.BatchResponseStatusRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchResponseStatusRequestBody();
            inValue.Body.id = id;
            PabInvestNew.CreditinfoService.BatchResponseStatusResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchResponseStatus(inValue);
            return retVal.Body.BatchResponseStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchResponseStatusResponse> PabInvestNew.CreditinfoService.ServiceSoap.BatchResponseStatusAsync(PabInvestNew.CreditinfoService.BatchResponseStatusRequest request) {
            return base.Channel.BatchResponseStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchResponseStatusResponse> BatchResponseStatusAsync(long id) {
            PabInvestNew.CreditinfoService.BatchResponseStatusRequest inValue = new PabInvestNew.CreditinfoService.BatchResponseStatusRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchResponseStatusRequestBody();
            inValue.Body.id = id;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchResponseStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PabInvestNew.CreditinfoService.BatchResponseChunkResponse PabInvestNew.CreditinfoService.ServiceSoap.BatchResponseChunk(PabInvestNew.CreditinfoService.BatchResponseChunkRequest request) {
            return base.Channel.BatchResponseChunk(request);
        }
        
        public byte[] BatchResponseChunk(long id, int partNumber) {
            PabInvestNew.CreditinfoService.BatchResponseChunkRequest inValue = new PabInvestNew.CreditinfoService.BatchResponseChunkRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchResponseChunkRequestBody();
            inValue.Body.id = id;
            inValue.Body.partNumber = partNumber;
            PabInvestNew.CreditinfoService.BatchResponseChunkResponse retVal = ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchResponseChunk(inValue);
            return retVal.Body.BatchResponseChunkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchResponseChunkResponse> PabInvestNew.CreditinfoService.ServiceSoap.BatchResponseChunkAsync(PabInvestNew.CreditinfoService.BatchResponseChunkRequest request) {
            return base.Channel.BatchResponseChunkAsync(request);
        }
        
        public System.Threading.Tasks.Task<PabInvestNew.CreditinfoService.BatchResponseChunkResponse> BatchResponseChunkAsync(long id, int partNumber) {
            PabInvestNew.CreditinfoService.BatchResponseChunkRequest inValue = new PabInvestNew.CreditinfoService.BatchResponseChunkRequest();
            inValue.Body = new PabInvestNew.CreditinfoService.BatchResponseChunkRequestBody();
            inValue.Body.id = id;
            inValue.Body.partNumber = partNumber;
            return ((PabInvestNew.CreditinfoService.ServiceSoap)(this)).BatchResponseChunkAsync(inValue);
        }
    }
}
