//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ID { get; set; }
        public Nullable<int> ActiveID { get; set; }
        public string PIN { get; set; }
        public string RoleOfClient { get; set; }
        public string AGREEMENT_NO { get; set; }
        public string IndividualType { get; set; }
        public Nullable<decimal> GauarnteeAmount { get; set; }
        public string Currency { get; set; }
    }
}
