//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditInfoResult
    {
        public int Id { get; set; }
        public string Identifier { get; set; }
        public string Result { get; set; }
        public Nullable<int> ErrorTypeId { get; set; }
        public Nullable<int> IsML { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
