//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CreditinfoServiceEntities : DbContext
    {
        public CreditinfoServiceEntities()
            : base("name=CreditinfoServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreditInfoBatchId> CreditInfoBatchIds { get; set; }
        public virtual DbSet<CreditInfoResult> CreditInfoResults { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
    
        public virtual ObjectResult<TestCall_Result> TestCall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestCall_Result>("TestCall");
        }
    
        public virtual ObjectResult<GetPersonaData_intividualPI_Result> GetPersonaData_intividualPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPersonaData_intividualPI_Result>("GetPersonaData_intividualPI");
        }
    
        public virtual ObjectResult<GetInfoForContracts_CreditCardPI_Result> GetInfoForContracts_CreditCardPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_CreditCardPI_Result>("GetInfoForContracts_CreditCardPI");
        }
    
        public virtual ObjectResult<GetInfoForContracts_IntallmentPI_Result> GetInfoForContracts_IntallmentPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_IntallmentPI_Result>("GetInfoForContracts_IntallmentPI");
        }
    
        public virtual ObjectResult<GetInfoForContracts_NoNinstalmentPI_Result> GetInfoForContracts_NoNinstalmentPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_NoNinstalmentPI_Result>("GetInfoForContracts_NoNinstalmentPI");
        }
    }
}
