//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CreditinfoServiceEntities : DbContext
    {
        public CreditinfoServiceEntities()
            : base("name=CreditinfoServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreditInfoBatchId> CreditInfoBatchIds { get; set; }
        public virtual DbSet<CreditInfoResult> CreditInfoResults { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
    
        public virtual ObjectResult<GetPersonaData_intividualPI_Result> GetPersonaData_intividualPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPersonaData_intividualPI_Result>("GetPersonaData_intividualPI");
        }
    
        public virtual ObjectResult<GetInfoForContracts_CreditCardPI_Result> GetInfoForContracts_CreditCardPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_CreditCardPI_Result>("GetInfoForContracts_CreditCardPI");
        }
    
        public virtual ObjectResult<GetInfoForContracts_IntallmentPI_Result> GetInfoForContracts_IntallmentPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_IntallmentPI_Result>("GetInfoForContracts_IntallmentPI");
        }
    
        public virtual ObjectResult<GetInfoForContracts_NoNinstalmentPI_Result> GetInfoForContracts_NoNinstalmentPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_NoNinstalmentPI_Result>("GetInfoForContracts_NoNinstalmentPI");
        }
    
        public virtual ObjectResult<GetInfoForMail_Intallment_Gl_Result> GetInfoForMail_Intallment_Gl(string casenumber)
        {
            var casenumberParameter = casenumber != null ?
                new ObjectParameter("Casenumber", casenumber) :
                new ObjectParameter("Casenumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForMail_Intallment_Gl_Result>("GetInfoForMail_Intallment_Gl", casenumberParameter);
        }
    
        public virtual int SentByMail_GL(string casenumber, string claimid)
        {
            var casenumberParameter = casenumber != null ?
                new ObjectParameter("Casenumber", casenumber) :
                new ObjectParameter("Casenumber", typeof(string));
    
            var claimidParameter = claimid != null ?
                new ObjectParameter("claimid", claimid) :
                new ObjectParameter("claimid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SentByMail_GL", casenumberParameter, claimidParameter);
        }
    
        public virtual ObjectResult<GetInfoForContracts_CreditCard_Result> GetInfoForContracts_CreditCard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_CreditCard_Result>("GetInfoForContracts_CreditCard");
        }
    
        public virtual ObjectResult<GetInfoForContracts_CreditCardML_Result> GetInfoForContracts_CreditCardML()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_CreditCardML_Result>("GetInfoForContracts_CreditCardML");
        }
    
        public virtual ObjectResult<GetInfoForContracts_Intallment_Result> GetInfoForContracts_Intallment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_Intallment_Result>("GetInfoForContracts_Intallment");
        }
    
        public virtual ObjectResult<GetInfoForContracts_IntallmentML_Result> GetInfoForContracts_IntallmentML()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_IntallmentML_Result>("GetInfoForContracts_IntallmentML");
        }
    
        public virtual ObjectResult<GetInfoForContracts_NoNinstalment_Result> GetInfoForContracts_NoNinstalment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForContracts_NoNinstalment_Result>("GetInfoForContracts_NoNinstalment");
        }
    
        public virtual ObjectResult<GetInfoForMail_Intallment_ML_Result> GetInfoForMail_Intallment_ML(string casenumber)
        {
            var casenumberParameter = casenumber != null ?
                new ObjectParameter("Casenumber", casenumber) :
                new ObjectParameter("Casenumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoForMail_Intallment_ML_Result>("GetInfoForMail_Intallment_ML", casenumberParameter);
        }
    
        public virtual ObjectResult<GetPersonaData_Company_Result> GetPersonaData_Company()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPersonaData_Company_Result>("GetPersonaData_Company");
        }
    
        public virtual ObjectResult<GetPersonaData_intividual_Result> GetPersonaData_intividual()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPersonaData_intividual_Result>("GetPersonaData_intividual");
        }
    
        public virtual ObjectResult<GetPersonaData_intividualML_Result> GetPersonaData_intividualML()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPersonaData_intividualML_Result>("GetPersonaData_intividualML");
        }
    }
}
